### ISSUE TITLE
Const qualifier on `Canvas::getPixel()` breaks GPU-CPU synchronization scheduling

### ISSUE THREAD

**Issue by Sigmarik** [B05-232/plug-standard#54] opened 2023-11-28 12:26 UTC
`Canvas::getPixel` should load the canvas from GPU in certain cases, which is impossible to do without discarding the `const` qualifier.

**Comment by MeerkatBoss** [comment] 2023-11-28 12:32
Duplicate of #41

**Closed as completed** 2023-11-28 12:55 UTC
Labels: bug, duplicate, api
